# Generated by Django 5.0.6 on 2024-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='esic_temp_input_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoppr_id', models.IntegerField(unique=True)),
                ('esic_location', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_zipcode', models.BigIntegerField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_zipcode', models.BigIntegerField(blank=True, null=True)),
                ('esic_state_dispensary', models.CharField(max_length=100)),
                ('esic_district_dispensary', models.CharField(max_length=100)),
                ('dispensary_employee', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('sms', models.CharField(max_length=255)),
                ('nominee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nominee_relation', models.CharField(blank=True, null=True)),
                ('date_of_birth_family', models.DateField(blank=True, null=True)),
                ('bank_account_number', models.BigIntegerField(blank=True, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('esic_no', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
