# Generated by Django 5.0.6 on 2024-06-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esic_temp_input_table',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
