# Generated by Django 5.0.6 on 2024-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temp_app', '0002_alter_esic_temp_input_table_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='esic_credentials_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=255)),
                ('user_name', models.BigIntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
