# Generated by Django 5.0.6 on 2024-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temp_app', '0003_esic_credentials_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esic_temp_input_table',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
    ]
