# Generated by Django 5.0.6 on 2024-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temp_app', '0004_alter_esic_temp_input_table_date_of_joining'),
    ]

    operations = [
        migrations.CreateModel(
            name='esic_temp_output_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoppr_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('created_esic_no', models.BigIntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Temp_card_down_path', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
    ]
