# Generated by Django 5.0.6 on 2024-06-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temp_app', '0005_esic_temp_output_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esic_temp_output_table',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
